version: '3.5'
services:
  #PHP Service
  call_it:
    image: callit:project
    build:
      context: .
      dockerfile: Dockerfile
    container_name: call_it
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - suu_network
  # Nginx Service
  webserver_call_it:
    image: nginx:alpine
    container_name: webserver_call_it
    restart: unless-stopped
    tty: true
    ports:
      - "8889:8889"
    volumes:
     - ./:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      suu_network:
        aliases:
          - service_web
    command: [nginx-debug, '-g', 'daemon off;']
  # Mysql Service
  db:
    image: mysql:8.0
    container_name: dbmysql_callit
    tty: true
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=callit
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
    - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - suu_network
volumes:
  db:
    driver: local
#Docker Networks
networks:
  suu_network:
    name: suu_network
    external: false